import numpy as np
import matplotlib.pyplot as plt

## 2D Newton's method


Note: see the examples here: https://ece.uwaterloo.ca/~dwharder/NumericalAnalysis/10RootFinding/newtonND/


$X_{n+1} = X_{n} + \frac{f(x_n)}{f'(x_n)}$

$\delta x = \frac{f(x_n)}{f'(x_n)}$

$\rightarrow \delta x = f(x_n) J^{-1}(x_n) $;

$J(x_n)$ is the Jacobian matrix evaluated at $x_n$

$f(x_n)$ is the vector function $\rightarrow (f_1,f_2,f_3,...)$

## Example 1
$f_1(x,y) = x^2 + y^2 - 3 = 0$

$f_2(x,y) = -2x^2 - 0.5y^2 + 2 = 0$


Let's calcualte the Jacobian matrix


\begin{equation*}
J_{2,2} = 
\begin{pmatrix}
\partial_{x_1}f_1 & \partial_{x_2}f_1 \\
\partial_{x_1}f_2 & \partial_{x_2}f_2
\end{pmatrix}
\end{equation*}

So we will have: 


\begin{equation*}
J_{2,2} = 
\begin{pmatrix}
2x & 2y \\
-4x & -y
\end{pmatrix}
\end{equation*}

and

\begin{equation*}
F_{2,1} = 
\begin{pmatrix}
x^2+y^2-3\\
-2x^2-0.5y^2+2
\end{pmatrix}
\end{equation*}



In [37]:
def J(x,y):
    return np.array([[2*x,2*y],[-4*x,-y]])

def F(x,y):
    return np.array([[x**2+y**2-3],[-2*x**2 - 0.5*y**2 + 2]])

In [53]:
x = 1
y = 1
iteration = 5

for i in range(iteration):
    deltaX = np.matmul(np.linalg.inv(J(x,y)),F(x,y))
    x = x - deltaX[0][0]
    y = y - deltaX[1][0]

In [54]:
x,y

(0.5773502691896257, 1.632993161855452)

In [55]:
F(x,y)

array([[0.],
       [0.]])

## Example 2


\begin{equation*}
J_{2,2} = 
\begin{pmatrix}
2x-y & 2y-x \\
1-y& 1-x
\end{pmatrix}
\end{equation*}

and

\begin{equation*}
F_{2,1} = 
\begin{pmatrix}
x^2-xy+y^2-3\\
x+y-xy
\end{pmatrix}
\end{equation*}


In [58]:
def J(x,y):
    return np.array([[2*x-y,2*y-x],[1-y,1-x]])

def F(x,y):
    return np.array([[x**2-x*y+y**2-3],[x+y-x*y]])

In [59]:
x = -1.5
y = 0.5
iteration = 5

for i in range(iteration):
    deltaX = np.matmul(np.linalg.inv(J(x,y)),F(x,y))
    x = x - deltaX[0][0]
    y = y - deltaX[1][0]

In [60]:
x,y

(-1.3692054070924666, 0.5779175596145465)

In [62]:
F(x,y), F(y,x)

(array([[ 4.44089210e-16],
        [-1.11022302e-16]]),
 array([[ 0.00000000e+00],
        [-1.11022302e-16]]))