In [3]:
import numpy as np
import matplotlib.pyplot as plt

## 2D Newton's method




In the general sence and view, newton's method try to find the root using following algorithm (gif from Newton's method wikipedia)
<p><a href="https://commons.wikimedia.org/wiki/File:NewtonIteration_Ani.gif#/media/File:NewtonIteration_Ani.gif"><img src="https://upload.wikimedia.org/wikipedia/commons/e/e0/NewtonIteration_Ani.gif" alt="Illustration of Newton's method"></a>

    
So in each step we draw a tangent to the function at $X_n$ and find the point that the straight line cuts x axis (root of that line). That point will be $X_{n+1}$
    

$F(X) = (f_1, f_2, f_3, ...)^T$


$X = (x1,x2,x3,...)$

when we want to find the root of $F(X)$, then we set $F(X)=0$


Reminder of Jacobian Matrix:



\begin{equation*}
J_{2,2} = 
\begin{pmatrix}
\partial_{x_1}f_1 & \partial_{x_2}f_1 \\
\partial_{x_1}f_2 & \partial_{x_2}f_2
\end{pmatrix}
\end{equation*}


line equation: $Y-Y_0 = J(X-X_0)$ 

in which $J$ is the Jacobian matrix, $Y_0$ is $F(X_n)$ and $X_0$ is $X_n$. So we will have:

$y = J(X-X_n) + F(X_n)$

now if we set $y= 0$ (to find the root of the tangent line), and solve for $\Delta X = X - X_n$, we will have:

$\Delta X = - J^{-1}(X_n) F(X_n)$

Now we can update the value of $X_n$ using $\Delta X$. (Since $X_{n+1}$ is the root of tangent line)

$X_{n+1} = X_{n} + \Delta X$
    

## Example 1

Note: see the examples here: https://ece.uwaterloo.ca/~dwharder/NumericalAnalysis/10RootFinding/newtonND/

$f_1(x,y) = x^2 + y^2 - 3 = 0$

$f_2(x,y) = -2x^2 - 0.5y^2 + 2 = 0$


Let's calcualte the Jacobian matrix


So we will have: 


\begin{equation*}
J_{2,2} = 
\begin{pmatrix}
2x & 2y \\
-4x & -y
\end{pmatrix}
\end{equation*}

and

\begin{equation*}
F_{2,1} = 
\begin{pmatrix}
x^2+y^2-3\\
-2x^2-0.5y^2+2
\end{pmatrix}
\end{equation*}



In [20]:
def J(X):
    return np.array([[2*X[0][0],2*X[1][0]],[-4*X[0][0],-X[1][0]]])

def F(X):
    return np.array([[X[0][0]**2+X[1][0]**2-3],[-2*X[0][0]**2 - 0.5*X[1][0]**2 + 2]])

In [21]:
X = np.array((1,1)).reshape((2,1))
iteration = 5

for i in range(iteration):
    deltaX = np.matmul(np.linalg.inv(J(X)),F(X))
    X = X - deltaX

In [22]:
X

array([[0.57735027],
       [1.63299316]])

In [17]:
F(X)

array([[0.],
       [0.]])

## Example 2


\begin{equation*}
J_{2,2} = 
\begin{pmatrix}
2x-y & 2y-x \\
1-y& 1-x
\end{pmatrix}
\end{equation*}

and

\begin{equation*}
F_{2,1} = 
\begin{pmatrix}
x^2-xy+y^2-3\\
x+y-xy
\end{pmatrix}
\end{equation*}


In [23]:
def J(X):
    return np.array([[2*X[0][0]-X[1][0],2*X[1][0]-X[0][0]],[1-X[1][0],1-X[0][0]]])

def F(Y):
    return np.array([[X[0][0]**2-X[0][0]*X[1][0]+X[1][0]**2-3],[X[0][0]+X[1][0]-X[0][0]*X[1][0]]])

In [28]:
X = np.array((-1.5,0.5)).reshape((2,1))
iteration = 5

for i in range(iteration):
    deltaX = np.matmul(np.linalg.inv(J(X)),F(X))
    X = X - deltaX

In [29]:
X

array([[-1.36920541],
       [ 0.57791756]])

In [30]:
F(X)

array([[ 4.44089210e-16],
       [-1.11022302e-16]])