<a href="https://colab.research.google.com/github/alifele/Computational-Physics/blob/main/Great%20Notes/Reshaping_in_python_and_matlab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this note I am going to show that the reshaping in matlab and python happens with different results.

In [1]:
import numpy as np

In [11]:
a = np.arange(1,17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
a.reshape((2,8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

the same code in matlab will result in:
```matlab
a = [1:16];
a = reshape(a,2,8)

>> a =
     1     3     5     7     9    11    13    15
     2     4     6     8    10    12    14    16
```

In [13]:
a.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

the same code in matlab will result in:
```matlab
a = [1:16];
a = reshape(a,4,4)

>> a =
     1     5     9    13
     2     6    10    14
     3     7    11    15
     4     8    12    16

```

In [14]:
b = np.arange(1,65)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [15]:
b.reshape(4,4,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[33, 34, 35, 36],
        [37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60],
        [61, 62, 63, 64]]])

the same code in matlab will result in:
```matlab
a = [1:64];
a = reshape(a,4,4,4)

>> a(:,:,1) =
     1     5     9    13
     2     6    10    14
     3     7    11    15
     4     8    12    16

>> a(:,:,2) =
    17    21    25    29
    18    22    26    30
    19    23    27    31
    20    24    28    32

>> a(:,:,3) =
    33    37    41    45
    34    38    42    46
    35    39    43    47
    36    40    44    48

>> a(:,:,4) =
    49    53    57    61
    50    54    58    62
    51    55    59    63
    52    56    60    64

```